server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whistle
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

