server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/posts
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true





#  -- Create the 'posts' schema
#  CREATE SCHEMA IF NOT EXISTS posts;
#
#  -- Use the 'posts' schema
#  USE posts;
#
#  -- Create the 'post' table
#  CREATE TABLE IF NOT EXISTS post (
#  post_id INT AUTO_INCREMENT PRIMARY KEY,
#  owner_id INT,
#  content TEXT,
#  post_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#  image_path VARCHAR(255)
#  );

